[package]
name = "wgpu-prefix-sum-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "28.0.0"
bytemuck = "1.24.0"
anyhow = "1.0.100"
pollster = "0.4.0"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "bench"
harness = false
